import { type LucideIcon } from "lucide-react"

import {
  // General & Dashboard
  LayoutDashboard, Grid, Home, Activity, Gauge, Target, Rocket, Zap,
  Bell, Search, Menu, Filter, Sliders, MoreHorizontal, MoreVertical,
  Loader2, Globe, MapPin, Calendar, CalendarDays, Clock, Timer, Hourglass,
  
  // Finance & Payments (Invoices, Bills, Cash)
  Banknote, DollarSign, Euro, PoundSterling, Currency, Wallet, CreditCard,
  Receipt, ReceiptText, PiggyBank, Coins, Calculator, Landmark, History,
  TrendingUp, TrendingDown, Percent, BadgeDollarSign, BadgePercent, Gem,
  ShoppingBag, ShoppingCart, ShoppingBasket, Tag, Tags, Gift, Truck, Package,
  
  // Media & Studio
  Image as ImageIcon, ImagePlus, Camera, Video, VideoOff, Mic, Mic2, MicOff,
  Music, Volume, Volume2, VolumeX, Clapperboard, Film, Aperture, Crop,
  Wand2, Palette, Brush, PenTool, Highlighter, Layers, Maximize, Minimize,
  Play, Pause, StopCircle, FastForward, Rewind, SkipBack, SkipForward,
  MonitorPlay, Speaker, Cast, Airplay,
  
  // Users & Teams
  Users, User, UserCog, UserPlus, UserMinus, UserCheck, UserX, UserCircle,
  Users2, Baby, PersonStanding, GraduationCap, Stethoscope, Briefcase,
  Fingerprint, Contact, Crown, Smile, Heart, ThumbsUp, ThumbsDown,
  
  // Documents, Records & Files
  FileText, File, FilePlus, FileMinus, FileEdit, FileCheck, FileX,
  FileSymlink, FileArchive, FileInput, FileOutput, FileCode, FileQuestion,
  Folder, FolderOpen, FolderPlus, FolderMinus, Archive, Database, Server,
  HardDrive, Cloud, CloudRain, Save, Printer, Clipboard, ClipboardList,
  ClipboardCheck, ClipboardEdit, StickyNote, Book, Bookmark,
  
  // Communication
  MessageSquare, MessageCircle, MessageSquarePlus, Mail, MailOpen, Send,
  Reply, ReplyAll, Forward, Inbox, Phone, PhoneCall, PhoneIncoming,
  PhoneOutgoing, Share, Share2, Link, AtSign, Hash,
  
  // Charts & Analytics
  BarChart, BarChart2, BarChart3, PieChart, LineChart, AreaChart,
  ScatterChart, CandlestickChart, 
  
  // Security & Settings
  Settings, Settings2, Shield, ShieldCheck, ShieldAlert, Lock, Unlock,
  Key, Eye, EyeOff, ToggleLeft, ToggleRight, SwitchCamera, Battery,
  Wifi, Bluetooth, Power, LogOut, LogIn, RefreshCw, RefreshCcw,
  
  // UI & Arrows
  ArrowUp, ArrowDown, ArrowLeft, ArrowRight, ArrowUpRight, ArrowDownLeft,
  ChevronUp, ChevronDown, ChevronLeft, ChevronRight, ChevronsUp,
  ChevronsDown, ChevronsLeft, ChevronsRight, CornerDownRight, CornerUpLeft,
  Plus, Minus, X, Check, CheckSquare, CheckCircle2, AlertCircle, AlertTriangle,
  Info, HelpCircle, Trash, Trash2, Edit, Edit2, Copy, ExternalLink,
  GripVertical, GripHorizontal, MousePointer, Move, Type, Braces, Terminal
} from "lucide-react";

export const ICONS: Record<string, any> = {
  // --- Dashboard & Navigation ---
  "LayoutDashboard": LayoutDashboard,
  "Grid": Grid,
  "Home": Home,
  "Activity": Activity,
  "Gauge": Gauge,
  "Target": Target,
  "Rocket": Rocket,
  "Zap": Zap,
  "Bell": Bell,
  "Search": Search,
  "Menu": Menu,
  "Filter": Filter,
  "Sliders": Sliders,
  "MoreHorizontal": MoreHorizontal,
  "MoreVertical": MoreVertical,
  "Loader2": Loader2,
  "Globe": Globe,
  "MapPin": MapPin,
  "Calendar": Calendar,
  "CalendarDays": CalendarDays,
  "Clock": Clock,
  "Timer": Timer,
  "Hourglass": Hourglass,

  // --- Finance (Invoice, Bill, Cash, Payment) ---
  "Banknote": Banknote,
  "DollarSign": DollarSign,
  "Euro": Euro,
  "PoundSterling": PoundSterling,
  "Currency": Currency,
  "Wallet": Wallet,
  "CreditCard": CreditCard,
  "Receipt": Receipt,
  "ReceiptText": ReceiptText,
  "PiggyBank": PiggyBank,
  "Coins": Coins,
  "Calculator": Calculator,
  "Landmark": Landmark,
  "History": History,
  "TrendingUp": TrendingUp,
  "TrendingDown": TrendingDown,
  "Percent": Percent,
  "BadgeDollarSign": BadgeDollarSign,
  "BadgePercent": BadgePercent,
  "Gem": Gem,
  "ShoppingBag": ShoppingBag,
  "ShoppingCart": ShoppingCart,
  "ShoppingBasket": ShoppingBasket,
  "Tag": Tag,
  "Tags": Tags,
  "Gift": Gift,
  "Truck": Truck,
  "Package": Package,

  // --- Media & Studio ---
  "Image": ImageIcon,
  "ImagePlus": ImagePlus,
  "Camera": Camera,
  "Video": Video,
  "VideoOff": VideoOff,
  "Mic": Mic,
  "Mic2": Mic2,
  "MicOff": MicOff,
  "Music": Music,
  "Volume": Volume,
  "Volume2": Volume2,
  "VolumeX": VolumeX,
  "Clapperboard": Clapperboard,
  "Film": Film,
  "Aperture": Aperture,
  "Crop": Crop,
  "Wand2": Wand2,
  "Palette": Palette,
  "Brush": Brush,
  "PenTool": PenTool,
  "Highlighter": Highlighter,
  "Layers": Layers,
  "Maximize": Maximize,
  "Minimize": Minimize,
  "Play": Play,
  "Pause": Pause,
  "StopCircle": StopCircle,
  "FastForward": FastForward,
  "Rewind": Rewind,
  "SkipBack": SkipBack,
  "SkipForward": SkipForward,
  "MonitorPlay": MonitorPlay,
  "Speaker": Speaker,
  "Cast": Cast,
  "Airplay": Airplay,

  // --- Users & Teams ---
  "Users": Users,
  "User": User,
  "UserCog": UserCog,
  "UserPlus": UserPlus,
  "UserMinus": UserMinus,
  "UserCheck": UserCheck,
  "UserX": UserX,
  "UserCircle": UserCircle,
  "Users2": Users2,
  "Baby": Baby,
  "PersonStanding": PersonStanding,
  "GraduationCap": GraduationCap,
  "Stethoscope": Stethoscope,
  "Briefcase": Briefcase,
  "Fingerprint": Fingerprint,
  "Contact": Contact,
  "Crown": Crown,
  "Smile": Smile,
  "Heart": Heart,
  "ThumbsUp": ThumbsUp,
  "ThumbsDown": ThumbsDown,

  // --- Documents, Records & Files ---
  "FileText": FileText,
  "File": File,
  "FilePlus": FilePlus,
  "FileMinus": FileMinus,
  "FileEdit": FileEdit,
  "FileCheck": FileCheck,
  "FileX": FileX,
  "FileSymlink": FileSymlink,
  "FileArchive": FileArchive,
  "FileInput": FileInput,
  "FileOutput": FileOutput,
  "FileCode": FileCode,
  "FileQuestion": FileQuestion,
  "Folder": Folder,
  "FolderOpen": FolderOpen,
  "FolderPlus": FolderPlus,
  "FolderMinus": FolderMinus,
  "Archive": Archive,
  "Database": Database,
  "Server": Server,
  "HardDrive": HardDrive,
  "Cloud": Cloud,
  "CloudRain": CloudRain,
  "Save": Save,
  "Printer": Printer,
  "Clipboard": Clipboard,
  "ClipboardList": ClipboardList,
  "ClipboardCheck": ClipboardCheck,
  "ClipboardEdit": ClipboardEdit,
  "StickyNote": StickyNote,
  "Book": Book,
  "Bookmark": Bookmark,

  // --- Communication ---
  "MessageSquare": MessageSquare,
  "MessageCircle": MessageCircle,
  "MessageSquarePlus": MessageSquarePlus,
  "Mail": Mail,
  "MailOpen": MailOpen,
  "Send": Send,
  "Reply": Reply,
  "ReplyAll": ReplyAll,
  "Forward": Forward,
  "Inbox": Inbox,
  "Phone": Phone,
  "PhoneCall": PhoneCall,
  "PhoneIncoming": PhoneIncoming,
  "PhoneOutgoing": PhoneOutgoing,
  "Share": Share,
  "Share2": Share2,
  "Link": Link,
  "AtSign": AtSign,
  "Hash": Hash,

  // --- Charts & Analytics ---
  "BarChart": BarChart,
  "BarChart2": BarChart2,
  "BarChart3": BarChart3,
  "PieChart": PieChart,
  "LineChart": LineChart,
  "AreaChart": AreaChart,
  "ScatterChart": ScatterChart,
  "CandlestickChart": CandlestickChart,

  // --- Security & Settings ---
  "Settings": Settings,
  "Settings2": Settings2,
  "Shield": Shield,
  "ShieldCheck": ShieldCheck,
  "ShieldAlert": ShieldAlert,
  "Lock": Lock,
  "Unlock": Unlock,
  "Key": Key,
  "Eye": Eye,
  "EyeOff": EyeOff,
  "ToggleLeft": ToggleLeft,
  "ToggleRight": ToggleRight,
  "SwitchCamera": SwitchCamera,
  "Battery": Battery,
  "Wifi": Wifi,
  "Bluetooth": Bluetooth,
  "Power": Power,
  "LogOut": LogOut,
  "LogIn": LogIn,
  "RefreshCw": RefreshCw,
  "RefreshCcw": RefreshCcw,

  // --- UI Elements & Arrows ---
  "ArrowUp": ArrowUp,
  "ArrowDown": ArrowDown,
  "ArrowLeft": ArrowLeft,
  "ArrowRight": ArrowRight,
  "ArrowUpRight": ArrowUpRight,
  "ArrowDownLeft": ArrowDownLeft,
  "ChevronUp": ChevronUp,
  "ChevronDown": ChevronDown,
  "ChevronLeft": ChevronLeft,
  "ChevronRight": ChevronRight,
  "ChevronsUp": ChevronsUp,
  "ChevronsDown": ChevronsDown,
  "ChevronsLeft": ChevronsLeft,
  "ChevronsRight": ChevronsRight,
  "CornerDownRight": CornerDownRight,
  "CornerUpLeft": CornerUpLeft,
  "Plus": Plus,
  "Minus": Minus,
  "X": X,
  "Check": Check,
  "CheckSquare": CheckSquare,
  "CheckCircle2": CheckCircle2,
  "AlertCircle": AlertCircle,
  "AlertTriangle": AlertTriangle,
  "Info": Info,
  "HelpCircle": HelpCircle,
  "Trash": Trash,
  "Trash2": Trash2,
  "Edit": Edit,
  "Edit2": Edit2,
  "Copy": Copy,
  "ExternalLink": ExternalLink,
  "GripVertical": GripVertical,
  "GripHorizontal": GripHorizontal,
  "MousePointer": MousePointer,
  "Move": Move,
  "Type": Type,
  "Braces": Braces,
  "Terminal": Terminal
};

/**
 * Public list of icon names (sorted)
 * Used for the Dropdown options
 */
export const ICON_OPTIONS = Object.keys(ICONS).sort()

/**
 * Safe icon getter with fallback
 */
export function getIcon(name: string): LucideIcon {
  return ICONS[name] || FileQuestion
}